# Generated by Django 4.2.8 on 2024-05-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0002_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
