# Generated by Django 4.2.8 on 2024-05-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0005_accounts_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='studID',
            field=models.IntegerField(max_length=7),
        ),
    ]
