# Generated by Django 4.2.8 on 2024-05-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0006_remove_accounts_last_login_alter_accounts_studid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='password',
            new_name='set_password',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='studID',
            field=models.IntegerField(),
        ),
    ]
