# Generated by Django 4.2.8 on 2024-05-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0007_rename_password_accounts_set_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
