# Generated by Django 4.2.8 on 2024-05-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0009_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='password',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='personal_emailadd',
            field=models.EmailField(max_length=254),
        ),
    ]
