# Generated by Django 4.2.8 on 2024-05-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0010_remove_accounts_groups_remove_accounts_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
