# Generated by Django 4.2.8 on 2024-05-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0011_delete_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('grade_file', models.FileField(upload_to='grades/')),
                ('cor_file', models.FileField(upload_to='cor/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_system.studentinfo')),
            ],
        ),
    ]
