# Generated by Django 4.2.8 on 2024-05-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0013_rename_student_requirement_studid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='id',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='studID',
        ),
        migrations.AddField(
            model_name='requirement',
            name='student_ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
