# Generated by Django 4.2.8 on 2024-05-27 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0014_remove_requirement_id_remove_requirement_studid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
