# Generated by Django 4.2.8 on 2024-05-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0015_delete_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ID', models.IntegerField(default=0)),
                ('semester', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('grade_file', models.FileField(upload_to='grades/')),
                ('cor_file', models.FileField(upload_to='cor/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
