# Generated by Django 4.2.8 on 2024-05-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0016_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
