# Generated by Django 4.2.8 on 2024-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0017_requirement_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='scholars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_ID', models.IntegerField(default=0)),
                ('student_ID', models.IntegerField(default=0)),
                ('scholar_type', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
