# Generated by Django 4.2.8 on 2024-05-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0018_scholars'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholars',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
    ]
