# Generated by Django 4.2.8 on 2024-05-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0019_scholars_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholars',
            old_name='status',
            new_name='scholar_status',
        ),
    ]
