# Generated by Django 4.2.8 on 2024-05-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0021_scholars_remarks_scholars_year_studentinfo_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='student_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_system.studentinfo'),
        ),
    ]
