# Generated by Django 4.2.8 on 2024-05-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0022_alter_requirement_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='student_ID',
            field=models.IntegerField(default=0),
        ),
    ]
