# Generated by Django 4.2.8 on 2024-05-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0023_alter_requirement_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.RemoveField(
            model_name='scholars',
            name='id',
        ),
        migrations.AlterField(
            model_name='scholars',
            name='scholar_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scholars',
            name='student_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_system.studentinfo'),
        ),
    ]
