# Generated by Django 4.2.8 on 2024-05-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0026_remove_scholars_student_id_delete_requirement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='scholars',
            fields=[
                ('scholar_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('scholar_type', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('gpa', models.FloatField()),
                ('year', models.CharField(max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('scholar_status', models.CharField(default='ACTIVE', max_length=10)),
                ('studID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_system.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('grade_file', models.FileField(upload_to='grades/')),
                ('cor_file', models.FileField(upload_to='cor/')),
                ('schoolid_file', models.FileField(upload_to='schoolid/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('units', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(default='SCHOLAR', max_length=10)),
                ('studID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_system.studentinfo')),
            ],
        ),
    ]
