# Generated by Django 4.2.8 on 2024-05-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0029_alter_studentinfo_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.CharField(default='NON_SCHOLAR', max_length=10),
        ),
    ]
