# Generated by Django 4.2.8 on 2024-06-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0030_alter_requirement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.CharField(default='SCHOLAR', max_length=10),
        ),
        migrations.CreateModel(
            name='applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_file', models.FileField(blank=True, null=True, upload_to='cor_files/')),
                ('grade_file', models.FileField(blank=True, null=True, upload_to='grade_files/')),
                ('schoolid_file', models.FileField(blank=True, null=True, upload_to='schoolid_files/')),
                ('scholar_type', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('studID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_system.studentinfo')),
            ],
        ),
    ]
