# Generated by Django 4.2.8 on 2024-06-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0031_alter_requirement_type_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='cor_file',
            field=models.FileField(blank=True, null=True, upload_to='applicant/cor_files/'),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='grade_file',
            field=models.FileField(blank=True, null=True, upload_to='applicant/grade_files/'),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='schoolid_file',
            field=models.FileField(blank=True, null=True, upload_to='applicant/schoolid_files/'),
        ),
    ]
