# Generated by Django 4.2.8 on 2024-06-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0033_alter_applicants_cor_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='cor_file',
            field=models.FileField(blank=True, null=True, upload_to='applicants/cor_pic/'),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='grade_file',
            field=models.FileField(blank=True, null=True, upload_to='applicants/grade_pic'),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='schoolid_file',
            field=models.FileField(blank=True, null=True, upload_to='applicants/schoolid_pic'),
        ),
    ]
