# Generated by Django 4.2.8 on 2024-06-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0036_alter_applicants_cor_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
