# Generated by Django 5.0.2 on 2024-06-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0037_applicants_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholars',
            name='semester',
            field=models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='scholars',
            name='scholar_type',
            field=models.CharField(choices=[('CHED', [('Full Merit', 'CHED - Full Merit'), ('Half Merit', 'CHED - Half Merit'), ('Tulong Dunong Program', 'CHED - Tulong Dunong Program'), ('Tertiary Education Subsidy', 'CHED - Tertiary Education Subsidy'), ('Coscho', 'CHED - Coscho')]), ('LGU', [('ATESAP', 'LGU - ATESAP'), ('DOST Undergrad', 'LGU - DOST Undergrad'), ('With High Honor', 'LGU - With High Honor')]), ('NGU', [("Nature's Spring Foundation Inc", "NGU - Nature's Spring Foundation Inc"), ('Lifebank Foundation', 'NGU - Lifebank Foundation')])], max_length=100),
        ),
    ]
