# Generated by Django 5.0.2 on 2024-06-07 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0039_scholars_date_added_scholars_total_units_enrolled'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scholars',
            unique_together={('scholar_ID', 'studID')},
        ),
    ]
