# Generated by Django 5.0.2 on 2024-06-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0040_alter_scholars_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scholars',
            unique_together=set(),
        ),
    ]
