# Generated by Django 5.0.2 on 2024-06-07 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_system', '0044_remove_scholars_amount_remove_scholars_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholars',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scholars',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scholars',
            name='gpa',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholars',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholars',
            name='scholar_status',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='scholars',
            name='semester',
            field=models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='scholars',
            name='total_units_enrolled',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scholars',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='SemesterDetails',
        ),
    ]
